
dataset: weibo
qwen_path: /home/lyq/Model/Qwen2.5-72B-Instruct-GPTQ-Int8
root_path: /home/lyq/DataSet/FakeNews/weibo_dataset
batch_size: 256
rationale_name: cs
few_shot:
  enable: false
  num_few_shot: 4
  few_shot_dir: /home/lyq/DataSet/FakeNews/LLMFND_few_shot
QwenConfig:
  gpu_memory_utilization: 0.8
  tensor_parallel_size: 2
  temperature: 0.7
  top_p: 0.8
  repetition_penalty: 1.05
  max_tokens: 512