# parser.add_argument('--dataset', type=str,default='gossipcop')
#parser.add_argument('--qwen_path', type=str,default='/media/lyq/d/Model/Qwen2-VL-72B-Instruct-GPTQ-Int4')
#parser.add_argument('--root_path', type=str,default='/home/lyq/DataSet/FakeNews/gossipcop')
#parser.add_argument('--rationale_name',type=str,default='multi')

dataset: gossipcop
qwen_path: /home/lyq/Model/Qwen2-VL-72B-Instruct-GPTQ-Int4
root_path: /home/lyq/DataSet/FakeNews/gossipcop
model_type: remote
rationale_name: multi